// <auto-generated />
using System;
using CorpServe.Presistence.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorpServe.Presistence.Migrations
{
    [DbContext(typeof(CorpServeDbContext))]
    [Migration("20260418153726_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("AIEstimationSequence");

            modelBuilder.HasSequence<int>("ChatRoomSequence");

            modelBuilder.HasSequence<int>("MessageSequence");

            modelBuilder.HasSequence<int>("NotificationSequence");

            modelBuilder.HasSequence<int>("PaymentSequence");

            modelBuilder.HasSequence<int>("ProfileDocumentSequence");

            modelBuilder.HasSequence<int>("ProposalSequence");

            modelBuilder.HasSequence<int>("RatingSequence");

            modelBuilder.HasSequence<int>("RequestAttachmentSequence");

            modelBuilder.HasSequence<int>("RequestProgressSequence");

            modelBuilder.HasSequence<int>("RequestSequence");

            modelBuilder.HasSequence<int>("SLAContractSequence");

            modelBuilder.HasSequence<int>("UserProfileSequence");

            modelBuilder.HasSequence<int>("VendorCertificateSequence");

            modelBuilder.Entity("CorpServe.Domain.Entities.AIEstimateModule.AIEstimation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("'AIE-' + RIGHT('000' + CAST(NEXT VALUE FOR AIEstimationSequence AS VARCHAR(3)), 3)");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EstimatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("AIEstimation", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.ChatModule.ChatRoom", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValueSql("'CHR-' + RIGHT('000' + CAST(NEXT VALUE FOR ChatRoomSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VendorId");

                    b.ToTable("ChatRooms", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsecutiveDelayedSlaCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentOverdueWarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("UserValidPhoneCheck", "PhoneNumber Like '01[0125]%' and PhoneNumber Not Like '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.IdentityModule.ProfileDocument", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("'PD-' + RIGHT('000' + CAST(NEXT VALUE FOR ProfileDocumentSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileDocuments", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.IdentityModule.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("'UP-' + RIGHT('000' + CAST(NEXT VALUE FOR UserProfileSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("CompanyLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("VendorStars")
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValueSql("'MSG-' + RIGHT('000' + CAST(NEXT VALUE FOR MessageSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("ChatRoomId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MediaMimeType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("MediaSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Sender")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId", "SentAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.NotificationModule.SystemNotification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("'N-' + RIGHT('000' + CAST(NEXT VALUE FOR NotificationSequence AS VARCHAR(3)), 3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RelatedEntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RecipientId", "IsRead", "CreatedAt");

                    b.ToTable("SystemNotifications", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.PaymentModule.Payment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValueSql("'PAY-' + RIGHT('000' + CAST(NEXT VALUE FOR PaymentSequence AS VARCHAR(3)), 3)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Commision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MerchantOrderId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("PaymobIntentionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymobTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PayoutCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayoutFailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PayoutReference")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PayoutStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("NotStarted");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("VendorNetAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("WebhookRawStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("WebhookReceivedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MerchantOrderId")
                        .IsUnique();

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.HasIndex("PaymentStatus", "CreatedAt");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.ProposalModule.Proposal", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("'P-' + RIGHT('000' + CAST(NEXT VALUE FOR ProposalSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("ClientRejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ClientResponseAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProposalStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProposalType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProposedDeadline")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ProposedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("VendorId", "ProposalType", "ProposalStatus");

                    b.ToTable("Proposals", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.ProposalModule.SLAContract", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("'SLA-' + RIGHT('000' + CAST(NEXT VALUE FOR SLAContractSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ContractPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProposalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SLAStatus")
                        .HasColumnType("int");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("VendorId", "SLAStatus");

                    b.ToTable("SLAContracts", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.RatingModule.Rating", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValueSql("'RAT-' + RIGHT('000' + CAST(NEXT VALUE FOR RatingSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.RequestModule.Request", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("'REQ-' + RIGHT('000' + CAST(NEXT VALUE FOR RequestSequence AS VARCHAR(3)), 3)");

                    b.Property<decimal>("BudgetMax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BudgetMin")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CateogryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpectedDeadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CateogryId");

                    b.HasIndex("RequestStatus", "CateogryId");

                    b.HasIndex("ClientId", "RequestStatus", "CateogryId", "CreatedAt");

                    b.ToTable("Requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_Requests_Discription_MaxLength", "LEN([Discription]) <= 500");
                        });
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.RequestModule.RequestAttachment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("'REQA-' + RIGHT('000' + CAST(NEXT VALUE FOR RequestAttachmentSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestAttachments", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.SpecializedCategoryModule.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("'C-' + RIGHT('000' + CAST(NEXT VALUE FOR CategorySequence AS VARCHAR(3)), 3)");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.SpecializedCategoryModule.VendorCategory", b =>
                {
                    b.Property<string>("VendorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("VendorId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorCategories", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.VendorVerifyModule.VendorCertificate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("'VC-' + RIGHT('000' + CAST(NEXT VALUE FOR VendorCertificateSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("CertificateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorVerifyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("VendorVerifyId");

                    b.ToTable("VendorCertificates", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.VendorVerifyModule.VendorVerify", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("'V-' + RIGHT('000' + CAST(NEXT VALUE FOR VendorSequence AS VARCHAR(3)), 3)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorVerifications", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.AIEstimateModule.AIEstimation", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.RequestModule.Request", "Request")
                        .WithOne("AIEstimation")
                        .HasForeignKey("CorpServe.Domain.Entities.AIEstimateModule.AIEstimation", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.ChatModule.ChatRoom", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Client")
                        .WithMany("ClientChatRooms")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Vendor")
                        .WithMany("VendorChatRooms")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", b =>
                {
                    b.OwnsOne("CorpServe.Domain.Entities.IdentityModule.UserPreference", "UserPreference", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("EmailNotification")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true)
                                .HasColumnName("UserPreference_EmailNotification");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("UserPreference_Id");

                            b1.Property<bool>("SystemNotification")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true)
                                .HasColumnName("UserPreference_SystemNotification");

                            b1.HasKey("ApplicationUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId");
                        });

                    b.Navigation("UserPreference")
                        .IsRequired();
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.IdentityModule.ProfileDocument", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.UserProfile", "Profile")
                        .WithMany("Documents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.IdentityModule.UserProfile", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("CorpServe.Domain.Entities.IdentityModule.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.Message", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.ChatModule.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.NotificationModule.SystemNotification", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.PaymentModule.Payment", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Client")
                        .WithMany("ClientPayments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.RequestModule.Request", "Request")
                        .WithOne("Payment")
                        .HasForeignKey("CorpServe.Domain.Entities.PaymentModule.Payment", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Vendor")
                        .WithMany("VendorPayments")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Request");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.ProposalModule.Proposal", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.RequestModule.Request", "Request")
                        .WithMany("Proposals")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Vendor")
                        .WithMany("Proposals")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.ProposalModule.SLAContract", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Client")
                        .WithMany("ClientSLAContracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.ProposalModule.Proposal", "Proposal")
                        .WithOne("SLAContract")
                        .HasForeignKey("CorpServe.Domain.Entities.ProposalModule.SLAContract", "ProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.RequestModule.Request", "Request")
                        .WithOne("SLAContract")
                        .HasForeignKey("CorpServe.Domain.Entities.ProposalModule.SLAContract", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Vendor")
                        .WithMany("VendorSLAContracts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Proposal");

                    b.Navigation("Request");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.RatingModule.Rating", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Client")
                        .WithMany("ClientRatings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.PaymentModule.Payment", "Payment")
                        .WithOne("Rating")
                        .HasForeignKey("CorpServe.Domain.Entities.RatingModule.Rating", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.RequestModule.Request", "Request")
                        .WithOne("Rating")
                        .HasForeignKey("CorpServe.Domain.Entities.RatingModule.Rating", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Vendor")
                        .WithMany("VendorRatings")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Payment");

                    b.Navigation("Request");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.RequestModule.Request", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.SpecializedCategoryModule.Category", "Category")
                        .WithMany("Requests")
                        .HasForeignKey("CateogryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Client")
                        .WithMany("Requests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CorpServe.Domain.Entities.RequestModule.RequestProgress", "RequestProgress", b1 =>
                        {
                            b1.Property<string>("RequestId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("RequestProgress_Description");

                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("RequestProgress_Id")
                                .HasDefaultValueSql("'REQP-' + RIGHT('000' + CAST(NEXT VALUE FOR RequestProgressSequence AS VARCHAR(3)), 3)");

                            b1.Property<int>("Percentage")
                                .HasColumnType("int")
                                .HasColumnName("RequestProgress_ProgressPercentage");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("RequestProgress_UpdatedAt");

                            b1.Property<string>("VendorId")
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("RequestProgress_VendorId");

                            b1.HasKey("RequestId");

                            b1.HasIndex("VendorId");

                            b1.ToTable("Requests");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");

                            b1.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Vendor")
                                .WithMany()
                                .HasForeignKey("VendorId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.Navigation("Vendor");
                        });

                    b.Navigation("Category");

                    b.Navigation("Client");

                    b.Navigation("RequestProgress")
                        .IsRequired();
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.RequestModule.RequestAttachment", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.RequestModule.Request", "Request")
                        .WithMany("RequestAttachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.SpecializedCategoryModule.Category", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "AdminUser")
                        .WithMany("Categories")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.SpecializedCategoryModule.VendorCategory", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.SpecializedCategoryModule.Category", "Category")
                        .WithMany("VendorCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Vendor")
                        .WithMany("VendorCategories")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.VendorVerifyModule.VendorCertificate", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.VendorVerifyModule.VendorVerify", "VendorVerify")
                        .WithMany("VendorCertificates")
                        .HasForeignKey("VendorVerifyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorVerify");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.VendorVerifyModule.VendorVerify", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.ChatModule.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.IdentityModule.ApplicationUser", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ClientChatRooms");

                    b.Navigation("ClientPayments");

                    b.Navigation("ClientRatings");

                    b.Navigation("ClientSLAContracts");

                    b.Navigation("Notifications");

                    b.Navigation("Proposals");

                    b.Navigation("Requests");

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("VendorCategories");

                    b.Navigation("VendorChatRooms");

                    b.Navigation("VendorPayments");

                    b.Navigation("VendorRatings");

                    b.Navigation("VendorSLAContracts");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.IdentityModule.UserProfile", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.PaymentModule.Payment", b =>
                {
                    b.Navigation("Rating");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.ProposalModule.Proposal", b =>
                {
                    b.Navigation("SLAContract");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.RequestModule.Request", b =>
                {
                    b.Navigation("AIEstimation");

                    b.Navigation("Payment");

                    b.Navigation("Proposals");

                    b.Navigation("Rating");

                    b.Navigation("RequestAttachments");

                    b.Navigation("SLAContract");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.SpecializedCategoryModule.Category", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("VendorCategories");
                });

            modelBuilder.Entity("CorpServe.Domain.Entities.VendorVerifyModule.VendorVerify", b =>
                {
                    b.Navigation("VendorCertificates");
                });
#pragma warning restore 612, 618
        }
    }
}
